# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :sU do |sU|
    sU.vm.box = "bento/ubuntu-22.04"
    sU.vm.box_download_insecure = true
    sU.vm.network :private_network, ip: "192.168.100.30"
    sU.vm.hostname = "sU"
    sU.vm.synced_folder ".", "/var/www/"
    sU.vm.provider "virtualbox" do |v|
        v.cpus = 4
        v.memory = 4056
    end

  end

end
